### ISSUE TITLE
Transformer imports not working since 6.0.4 (Rollup)

### ISSUE THREAD

**Issue by kling90** [sveltejs/svelte-preprocess#681]
**Describe the bug**
After upgrading svelte-preprocess from 6.0.3 to 6.0.4, transformer loading fails in our Rollup build setup.
The failure appears to come from a change in autoProcess.js where transformer loading switched to native dynamic import without a file extension

**Logs**
```
Cannot find module '/home/kling/dev/skalbar-2/apps/NewsListing/node_modules/svelte-preprocess/dist/transformers/globalStyle' imported from /home/kling/dev/apps/NewsListing/node_modules/svelte-preprocess/dist/autoProcess.js
```

**To Reproduce**

Reproduction project
https://stackblitz.com/edit/stackblitz-starters-hn2sedt5?file=package.json
StackBlitz does not show the full local error output, but is shown locally when downloading the project.

When diffing the files the import logic of transformers has changed abit, it's now mixing CommonJS and ESM.
https://www.diffchecker.com/CeZL35Jh/

The native async import statement needs an extenstion, if I add that on row 23 it works as expected.
```diff
-  const { transformer } = await import(`./transformers/${name}`);
+  const { transformer } = await import(`./transformers/${name}.js`);
```

**Expected behavior**
Transformer imports should resolve successfully, as in 6.0.3.

**Information about your project:**

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
Ubuntu 24.04.3 LTS (Windows WSL)

- `svelte-preprocess` version
6.0.4

- Whether your project uses Webpack or Rollup
Rollup

**Comment by kling90** [comment]
Just noticed there already was a PR for this, can close this when that is merged
https://github.com/sveltejs/svelte-preprocess/pull/680
